### ISSUE TITLE
Feature Request: Recognize Node.js based child directories

### ISSUE THREAD

**Issue by toedter** [nicojs/node-link-parent-bin#7]
In a polyglot project with different subprojects and different programming languages it would be great if link-to-parent would recognize if a directory contains a node.js based subproject. This could probably be done by checking for an existing package.json.

Furthermore this could be opted in with a new cli command line option, like --only-nodejs-child-directories

Instead of having a script like:  "postinstall": "link-parent-bin --child-directory-root lab3 && link-parent-bin --child-directory-root lab4 && link-parent-bin --child-directory-root lab5 && link-parent-bin --child-directory-root lab6 && link-parent-bin --child-directory-root lab7"

This could be shortened then to "postinstall": "link-parent-bin --only-nodejs-child-directories"

I am using link-to-parent in my Webapp Tutorial https://github.com/toedter/webapp-tutorial

**Comment by julien51** [comment]
Another approach would maybe to have an option to explicitly list the sub-directories which should be linked?

**Comment by nicojs** [comment]
Sorry for the late reply 😢 

What is a "nodejs child directory"? 

How about using `--filter <pattern>`. The `pattern` would need to be a valid [minimatch pattern](https://www.npmjs.com/package/minimatch). For example: `--filter lab.` 

I'm happy to except PRs

**Comment by toedter** [comment]
>What is a "nodejs child directory"?
a directory that contains the file package.json to indicate that this directory might then also contain a node_modules sub directory.

>I'm happy to except PRs
I'll take a look at it when I find some time...

>How about using --filter <pattern>
In polyglot projects you could have any directory structure (including node based sub projects on any level). With this approach you would have to defined several matchers.

**Comment by billba** [comment]
I think this would be solved neatly by #19
